In [1]:
import numpy as np
import os
from itertools import product

In [2]:
# Read comma separated data
data = np.loadtxt(os.path.join('Data', 'ex1data1.txt'), delimiter=',')
X, y = data[:, 0], data[:, 1]

m = y.size  # number of training examples

## Vectorized Prediction Calculation

In [3]:
# Add a column of ones to X. The numpy function stack joins arrays along a given axis. 
# The first axis (axis=0) refers to rows (training examples) 
# and second axis (axis=1) refers to columns (features).
X = np.stack([np.ones(m), X], axis=1)

In [4]:
# You need to return the following variables correctly
J = 0
theta = np.array([-1, 2])    

In [5]:
Y = np.dot(X, theta)

In [6]:
Y

array([11.2202, 10.0554, 16.0372, 13.0064, 10.7196, 15.7658, 13.9528,
       16.1562, 11.9724,  9.1092, 10.4214, 27.328 , 10.468 , 15.8168,
       10.2814,  9.7588, 11.7308,  9.2602, 11.8592, 13.1416, 11.3782,
       39.54  ,  9.9802, 11.6522, 10.1298, 36.89  , 24.656 , 20.914 ,
       25.352 , 43.406 ,  9.5048, 12.1788, 17.4964, 10.7836, 15.4222,
       14.8668, 15.1918, 10.2126, 24.672 , 11.7068,  9.8138, 12.765 ,
       22.416 , 10.5474, 14.6494, 13.1862,  9.1404, 10.6028, 22.4   ,
       10.0832, 14.0804,  9.6154, 13.8478, 14.2062, 11.6656, 11.7178,
       11.5484, 10.2794, 17.6204, 17.9072, 16.6508,  9.3586, 41.558 ,
       28.816 , 36.918 , 13.4364, 15.5902, 19.472 ,  9.9988, 39.682 ,
       19.272 , 13.669 , 11.0124, 13.4518,  9.0538, 12.0958, 14.0772,
        9.073 , 19.548 ,  9.2154, 10.4584,  9.3768, 11.7114, 18.5374,
       12.0318, 16.0344, 17.3604, 11.004 , 10.0408,  9.1188, 10.4154,
       14.2732, 10.7414,  9.6108, 15.5868, 25.788 ,  9.8738])

In [7]:
X[:,1]

array([ 6.1101,  5.5277,  8.5186,  7.0032,  5.8598,  8.3829,  7.4764,
        8.5781,  6.4862,  5.0546,  5.7107, 14.164 ,  5.734 ,  8.4084,
        5.6407,  5.3794,  6.3654,  5.1301,  6.4296,  7.0708,  6.1891,
       20.27  ,  5.4901,  6.3261,  5.5649, 18.945 , 12.828 , 10.957 ,
       13.176 , 22.203 ,  5.2524,  6.5894,  9.2482,  5.8918,  8.2111,
        7.9334,  8.0959,  5.6063, 12.836 ,  6.3534,  5.4069,  6.8825,
       11.708 ,  5.7737,  7.8247,  7.0931,  5.0702,  5.8014, 11.7   ,
        5.5416,  7.5402,  5.3077,  7.4239,  7.6031,  6.3328,  6.3589,
        6.2742,  5.6397,  9.3102,  9.4536,  8.8254,  5.1793, 21.279 ,
       14.908 , 18.959 ,  7.2182,  8.2951, 10.236 ,  5.4994, 20.341 ,
       10.136 ,  7.3345,  6.0062,  7.2259,  5.0269,  6.5479,  7.5386,
        5.0365, 10.274 ,  5.1077,  5.7292,  5.1884,  6.3557,  9.7687,
        6.5159,  8.5172,  9.1802,  6.002 ,  5.5204,  5.0594,  5.7077,
        7.6366,  5.8707,  5.3054,  8.2934, 13.394 ,  5.4369])

In [8]:
J = (1/2/m) * np.sum((Y - y)**2)
J

54.24245508201238

In [9]:
J = 0
for i in range(len(Y)):
    J += (Y[i] - y[i])**2
J /= 2*m
J

54.24245508201238

## Vectorized Gradient Descent

In [10]:
alpha = 0.1

In [11]:
theta0 = np.empty(2)
theta0

array([-1.,  2.])

In [12]:
sumgrad = np.zeros(len(theta))
# e.g. j = 0
for j in range(len(theta)):
    for i in range(m):
        sumgrad[j] += X[i,j] * (Y[i] - y[i])
sumgrad

array([ 919.6051    , 8663.96588216])

In [13]:
(Y - y) @ X

array([ 919.6051    , 8663.96588216])

## Feature Normalization 

In [14]:
# Load data
data = np.loadtxt(os.path.join('Data', 'ex1data2.txt'), delimiter=',')
X = data[:, :2]
y = data[:, 2]
m = y.size

# print out some data points
print('{:>8s}{:>8s}{:>10s}'.format('X[:,0]', 'X[:, 1]', 'y'))
print('-'*26)
for i in range(10):
    print('{:8.0f}{:8.0f}{:10.0f}'.format(X[i, 0], X[i, 1], y[i]))

  X[:,0] X[:, 1]         y
--------------------------
    2104       3    399900
    1600       3    329900
    2400       3    369000
    1416       2    232000
    3000       4    539900
    1985       4    299900
    1534       3    314900
    1427       3    198999
    1380       3    212000
    1494       3    242500


In [26]:
# You need to set these values correctly
## average value
mu = np.average(X, axis=0)
# standard deviation
sigma = np.std(X, axis=0)

In [31]:
## normalized feature
X_norm1 = (X - mu) / sigma

In [32]:
## for loop
X_norm2 = np.empty(X.shape)
for ind in product(*map(range, X.shape)):
    X_norm2[ind[0], ind[1]] = (X[ind[0], ind[1]] - mu[ind[1]]) / sigma[ind[1]]
np.allclose(X_norm1, X_norm2)

True